export const GLOSSARY = {
  DeFi: "Finanzas descentralizadas: servicios financieros sin bancos.",
  DEX: "Exchange descentralizado: permite intercambiar tokens sin intermediario.",
  CEX: "Exchange centralizado: una empresa que custodia y facilita compras/ventas.",
  TVL: "Valor Total Bloqueado: cuánto dinero hay depositado en un protocolo.",
  APY: "Interés anual estimado que podés ganar al depositar tu crypto.",
  Staking: "Bloquear crypto para ayudar a una red y recibir recompensas.",
  "Yield farming": "Buscar rendimientos moviendo fondos entre protocolos (más riesgo).",
  "Liquidity pool": "Fondo compartido para swaps; ganás comisiones, pero hay riesgos.",
  Slippage: "Diferencia entre el precio esperado y el precio final al hacer un trade.",
  Gas: "Costo de transacción en una blockchain (comisión).",
  "Layer 2": "Capa extra para hacer transacciones más baratas/rápidas (sobre una red base).",
  Bridge: "Puente para mover tokens entre blockchains. Suele ser un punto de riesgo.",
  Airdrop: "Regalo de tokens por usar un proyecto o cumplir condiciones.",
  Whitelist: "Lista de direcciones habilitadas para participar (ej. mint/venta).",
  NFT: "Token no fungible: un ítem digital único que vive en la blockchain.",
  Tokenomics: "Reglas del token: oferta, emisión, desbloqueos, incentivos.",
  "Market cap": "Capitalización: precio x cantidad de tokens (tamaño aproximado).",
  Volatility: "Qué tanto sube y baja el precio en poco tiempo.",
  Leverage: "Apalancamiento: operar con dinero prestado (aumenta riesgo).",
  Liquidation: "Cierre forzoso de tu posición si el precio va en contra.",
  Stablecoin: "Token que busca valer ~1 USD (o un valor estable).",
  Memecoin: "Token basado en meme; suele ser muy volátil y especulativo.",
  "Rug pull": "Estafa: se llevan la liquidez o abandonan el proyecto y el token cae.",
  Phishing: "Engaño para robar tu acceso (seed, claves, firmas).",
  KYC: "Verificación de identidad (documento) en un servicio.",
  AML: "Reglas anti-lavado de dinero que aplican algunas plataformas.",
  "Cold wallet": "Billetera fuera de internet (más segura) para guardar a largo plazo.",
  "Hot wallet": "Billetera conectada a internet (más cómoda, más expuesta).",
  "Seed phrase": "12/24 palabras para recuperar tu billetera. Nunca se comparte.",
  "Smart contract": "Programa en blockchain que ejecuta reglas automáticamente.",
  Oracle: "Servicio que trae datos del mundo real a la blockchain (ej. precios).",
  Halving: "Evento en Bitcoin que reduce a la mitad la emisión de nuevos BTC.",
  Mining: "Proceso de asegurar una red (PoW) y crear bloques, usando computación.",
  Validators: "Participantes que validan transacciones en redes PoS.",
  "On-chain": "Información registrada en la blockchain y visible públicamente.",
  ICO: "Venta inicial de tokens para financiar un proyecto (puede ser riesgosa).",
  "Bull market": "Mercado alcista: subidas generalizadas.",
  "Bear market": "Mercado bajista: caídas generalizadas.",
} as const;

export type GlossaryTermKey = keyof typeof GLOSSARY;

